ERROR_MISSING_MAIN = 1
ERROR_UNDEFINED_VARIABLE = 2
ERROR_UNEXPECTED_TYPE_FOR_EXPRESSION = 3
ERROR_NOT_A_FUNCTION = 4
ERROR_NOT_A_TUPLE = 5
ERROR_NOT_A_RECORD = 6
ERROR_NOT_A_LIST = 7
ERROR_UNEXPECTED_LAMBDA = 8
ERROR_UNEXPECTED_TYPE_FOR_PARAMETER = 9
ERROR_UNEXPECTED_TUPLE = 10
ERROR_UNEXPECTED_RECORD = 11
ERROR_UNEXPECTED_VARIANT = 12
ERROR_UNEXPECTED_LIST = 13
ERROR_UNEXPECTED_INJECTION = 14
ERROR_MISSING_RECORD_FIELDS = 15
ERROR_UNEXPECTED_RECORD_FIELDS = 16
ERROR_UNEXPECTED_FIELD_ACCESS = 17
ERROR_UNEXPECTED_VARIANT_LABEL = 18
ERROR_TUPLE_INDEX_OUT_OF_BOUNDS = 19
ERROR_UNEXPECTED_TUPLE_LENGTH = 20
ERROR_AMBIGUOUS_SUM_TYPE = 21
ERROR_AMBIGUOUS_VARIANT_TYPE = 22
ERROR_AMBIGUOUS_LIST = 23
ERROR_ILLEGAL_EMPTY_MATCHING = 24
ERROR_NONEXHAUSTIVE_MATCH_PATTERNS = 25
ERROR_UNEXPECTED_PATTERN_FOR_TYPE = 26
ERROR_DUPLICATE_RECORD_FIELDS = 27
ERROR_DUPLICATE_RECORD_TYPE_FIELDS = 28
ERROR_DUPLICATE_VARIANT_TYPE_FIELDS = 29
ERROR_DUPLICATE_FUNCTION_DECLARATION = 30

_ERROR_NAMES = {
    1: "ERROR_MISSING_MAIN",
    2: "ERROR_UNDEFINED_VARIABLE",
    3: "ERROR_UNEXPECTED_TYPE_FOR_EXPRESSION",
    4: "ERROR_NOT_A_FUNCTION",
    5: "ERROR_NOT_A_TUPLE",
    6: "ERROR_NOT_A_RECORD",
    7: "ERROR_NOT_A_LIST",
    8: "ERROR_UNEXPECTED_LAMBDA",
    9: "ERROR_UNEXPECTED_TYPE_FOR_PARAMETER",
    10: "ERROR_UNEXPECTED_TUPLE",
    11: "ERROR_UNEXPECTED_RECORD",
    12: "ERROR_UNEXPECTED_VARIANT",
    13: "ERROR_UNEXPECTED_LIST",
    14: "ERROR_UNEXPECTED_INJECTION",
    15: "ERROR_MISSING_RECORD_FIELDS",
    16: "ERROR_UNEXPECTED_RECORD_FIELDS",
    17: "ERROR_UNEXPECTED_FIELD_ACCESS",
    18: "ERROR_UNEXPECTED_VARIANT_LABEL",
    19: "ERROR_TUPLE_INDEX_OUT_OF_BOUNDS",
    20: "ERROR_UNEXPECTED_TUPLE_LENGTH",
    21: "ERROR_AMBIGUOUS_SUM_TYPE",
    22: "ERROR_AMBIGUOUS_VARIANT_TYPE",
    23: "ERROR_AMBIGUOUS_LIST",
    24: "ERROR_ILLEGAL_EMPTY_MATCHING",
    25: "ERROR_NONEXHAUSTIVE_MATCH_PATTERNS",
    26: "ERROR_UNEXPECTED_PATTERN_FOR_TYPE",
    27: "ERROR_DUPLICATE_RECORD_FIELDS",
    28: "ERROR_DUPLICATE_RECORD_TYPE_FIELDS",
    29: "ERROR_DUPLICATE_VARIANT_TYPE_FIELDS",
    30: "ERROR_DUPLICATE_FUNCTION_DECLARATION",
}

def error_name(code: int) -> str:
    return _ERROR_NAMES.get(code, f"ERROR_{code}")

class TypeCheckError(Exception):
    def __init__(self, code: int, message: str):
        self.code = code
        self.message = message
        super().__init__(message)

    def __str__(self) -> str:
        return f"{error_name(self.code)}:\n{self.message}"
